### ISSUE TITLE
Could not load library: gstreamer on OSX

### ISSUE THREAD

**Issue by toaler** [gstreamer-java/gst1-java-examples#1]
When trying to run CameraTest on OSX i get the following ULE exception when running from eclipse.  I've tried adding Library/Frameworks/GStreamer.framework/Versions/Current/lib/ to java.library.path but that doesn't seem to help.  Any suggestions?

Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library: gstreamer
    at org.freedesktop.gstreamer.lowlevel.GstNative.load(GstNative.java:53)
    at org.freedesktop.gstreamer.lowlevel.GstNative.load(GstNative.java:43)
    at org.freedesktop.gstreamer.Gst.<clinit>(Gst.java:77)
    at org.freedesktop.gstreamer.examples.CameraTest.main(CameraTest.java:22)

**Comment by neilcsmith-net** [comment]
Hi,

You could try adding that location to jna.library.path - java.library.path is irrelevant to anything but JNA finding its own native library.  

I can't help much further as I don't use OSX.  Please sign up and ask on the mailing list.  https://groups.google.com/forum/#!forum/gstreamer-java  There are people on there who have successfully used this code on OSX.

Thanks, Neil

**Comment by toaler** [comment]
Thanks.  Ok i've fixed that problem but hit another one with "Invalid native pointer" exceptions now.  I've posted to the gstreamer-java forum and waiting for the post to be approved before the public members can see...

**Comment by vinkobuble** [comment]
@toaler how did you fix it would you explain please?

**Comment by jmich41** [comment]
@toaler how have you fixed this problem?

**Comment by neilcsmith-net** [comment]
@jmich41 please follow up on the mailing list with your issue please.

**Comment by Zander-Labuschagne** [comment]
I get a similar exception on Windows 10, after I have installed the complete gstreamer framework. Do I need to add things to my class path or something?

Here is the exact exception:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library: gstreamer
	at org.freedesktop.gstreamer.lowlevel.GstNative.load(GstNative.java:56)
	at org.freedesktop.gstreamer.lowlevel.GstNative.load(GstNative.java:46)
	at org.freedesktop.gstreamer.lowlevel.GstAPI.<clinit>(GstAPI.java:37)
	at org.freedesktop.gstreamer.Gst.getVersion(Gst.java:144)
	at org.freedesktop.gstreamer.Gst.init(Gst.java:473)
	at org.freedesktop.gstreamer.examples.SwingPlayer.main(SwingPlayer.java:75)
```

**Comment by neilcsmith-net** [comment]
@Zander-Labuschagne please follow up on the mailing list. The examples are not set up for 32-bit on Windows 10, so make sure you're using a 64-bit JVM and 64-bit install of GStreamer.  If you are, try adding some debugging output to https://github.com/gstreamer-java/gst1-java-examples/blob/master/SwingPlayer/src/main/java/org/freedesktop/gstreamer/examples/Utils.java#L68 and see what is being picked up.  As a last step, you can set the `gstreamer.path` system property to the location of your GStreamer install.

**Comment by Zander-Labuschagne** [comment]
@neilcsmith-net Thanks, it's working now. I did not try anything for a few days but it just works now after adding a println for debugging. Maybe it got fixed in the couple of reboots or after the Windows update. I know I definitely rebooted after installing it so it was not the first reboot that fixed it. Thanks for your advice anyway.

**Comment by mike2moon** [comment]
> @Zander-Labuschagne please follow up on the mailing list. The examples are not set up for 32-bit on Windows 10, so make sure you're using a 64-bit JVM and 64-bit install of GStreamer. If you are, try adding some debugging output to https://github.com/gstreamer-java/gst1-java-examples/blob/master/SwingPlayer/src/main/java/org/freedesktop/gstreamer/examples/Utils.java#L68 and see what is being picked up. As a last step, you can set the `gstreamer.path` system property to the location of your GStreamer install.

Unfortunately a simple reboot didnt solve the issue for me when i got this error when trying to load up a web camera on a processing sketch.  But your last helped.  So for anyone who still has this problem, to set the system property to the location of your GStreamer install this line of code did it for me  System.setProperty("gstreamer.path",  "C:\\gstreamer\\1.0\\msvc_x86_64");
just replace the location to where your gstreamer installed it, which this was default by the way.  I just pointed mine to the msvc location because i also installed a wingw version just incase so you might have to change that last bit too if youre using another for whatever reason.    By the way i got line of code from chatgpt, although as smart as it is, it couldnt give me correct soltion to the "cant load gstreamer library" problem,  so credit goes yo you but since you didnt give the full details as to how, noobs like me who were browsing this forum looking for a fix were left confused with your explanation, so part credit goes for chatgtp. for clarifying.   :)  And this is no ones fualt as the library should have been installed/pointed to correclty but something is messing it up, a conflict and the automatic resoltuion i think keep deleting the correct path in favour of the wrong path im guess, but ill take this for now.   Thanks.
